# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: position_controllers/GripperActionController

    forward_command_controller_effort:
      type: forward_command_controller/ForwardCommandController

    impedance_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # arm_with_gripper_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 5.0
gripper_controller:
  ros__parameters:
    joint: finger_joint
# arm_with_gripper_controller:
#   ros__parameters:
#     joints:
#       - shoulder_pan_joint
#       - shoulder_lift_joint
#       - elbow_joint
#       - wrist_1_joint
#       - wrist_2_joint
#       - wrist_3_joint
#       - finger_joint
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#     allow_nonzero_velocity_at_trajectory_end: true

forward_command_controller_effort:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    interface_name: effort

impedance_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 5.0